modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="cross_tesseract"
version="0.1.0-dev"
displayName="CrossServer Tesseract"
description='''跨服超立方体：MySQL 权威频道、独占资源划拨与全群组加载配额。'''
[[dependencies.cross_tesseract]]
modId="neoforge"
type="required"
versionRange="[21.1.252,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.cross_tesseract]]
modId="ae2"
type="optional"
versionRange="[19.2.18]"
ordering="AFTER"
side="BOTH"
[[dependencies.cross_tesseract]]
modId="mekanism"
type="optional"
versionRange="[10.7.19,10.7.20)"
ordering="AFTER"
side="BOTH"
[[dependencies.cross_tesseract]]
modId="gtceu"
type="optional"
versionRange="[8.0.0]"
ordering="AFTER"
side="BOTH"
[[dependencies.cross_tesseract]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
