backend.enabled=true
cluster.id=test_gametest_9811630f4a
server.id=gametest
mysql.url=jdbc:mysql://127.0.0.1:13306/cross_tesseract?sslMode=DISABLED&allowPublicKeyRetrieval=true&connectTimeout=1500&socketTimeout=3000
mysql.user=ct_dev
mysql.password=ct_dev_only
redis.uri=redis://127.0.0.1:16379
chunkLoading.maxPerPlayer=2
